In [5]:
from numpy import array
from keras.models import Sequential
from keras.layers import GRU, Dense, Dropout        
from numpy import hstack

In [6]:
def split_sequence(sequence, n_step):
   x,y = list(), list() #x is data and y is label
   for i in range(len(sequence)):
       end_ix = i + n_step
   
       if end_ix > len(sequence) - 1: # In this -if- we want if data be beyond len(sequence)-1, the command will not continue and break.
          break
       seq_x, seq_y = sequence[i:end_ix,:] , sequence[end_ix,:] # whole column
       x.append(seq_x)
       y.append(seq_y)
   return array(x) , array(y)

Making Data:

In [7]:
seq1 = array([10,20,30,40,50,60,70,80,90])
seq2 = array([10,20,30,40,50,60,70,80,90])
seq3 = array([10,20,30,40,50,60,70,80,90])
   

seq1 = seq1.reshape((len(seq1),1)) #reshape: (9, 1)
seq2 = seq2.reshape((len(seq2),1)) #reshape: (9, 1)
seq3 = seq3.reshape((len(seq3),1)) #reshape: (9, 1)


dataset = hstack((seq1,seq2,seq3)) #function is used to stack the sequence of input arrays horizontally
dataset

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [40, 40, 40],
       [50, 50, 50],
       [60, 60, 60],
       [70, 70, 70],
       [80, 80, 80],
       [90, 90, 90]])

In [8]:
n_steps = 3 #timestep or look_up
x,y = split_sequence(dataset, n_steps)
print(x.shape,y.shape)   
   
print(f"{x[0]} | {y[0]}")

(6, 3, 3) (6, 3)
[[10 10 10]
 [20 20 20]
 [30 30 30]] | [40 40 40]


In [9]:
n_features = x.shape[2]
n_features

3

In [10]:
model = Sequential()

model.add(GRU(units=200, activation='tanh',  input_shape=(n_steps,n_features))) # tanh is best activation in gru but relu also is used

model.add(Dense(n_features)) #n-output  
   
model.compile(optimizer='RMSprop',loss='mse')

c:\Users\aksha\anaconda2\envs\aipytorch\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model.fit(x,y,epochs=800,verbose=1)

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru (GRU)                       │ (None, 200)            │       123,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │           603 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 247,208 (965.66 KB)

 Trainable params: 123,603 (482.82 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 123,605 (482.84 KB)

Testing

In [17]:
x_input = array([[10,10,10],[20,20,20],[30,30,30]])
x_input

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [18]:
x_input = x_input.reshape(1, n_steps, n_features)

yhat = model.predict(x_input,verbose=0) 
print(yhat)

[[40.152275 39.92604  39.930027]]
